export const INITIAL_STATE = {
    profile: null,
    loading: false,
};

export const userActions = {
    UPDATE_PROFILE_REQUEST: '@user/UPDATE_PROFILE_REQUEST',
    UPDATE_PROFILE_SUCCESS: '@user/UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_FAILURE: '@user/UPDATE_PROFILE_FAILURE',

    REGISTER_PROFILE_REQUEST: '@user/REGISTER_PROFILE_REQUEST',
    REGISTER_PROFILE_FAILURE: '@user/REGISTER_PROFILE_FAILURE',
    REGISTER_PROFILE_SUCCESS: '@user/REGISTER_PROFILE_SUCCESS',
};
